name: CI - Tests, Coverage & SonarCloud

on:
  push:
    branches: [ "main", "developer", "certification" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del cÃ³digo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov flake8 bandit

      - name: Linting con Flake8
        run: |
          flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 src --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics

      - name: Escaneo de seguridad con Bandit
        run: |
          bandit -r src -q || true

      - name: Ejecutar pruebas con cobertura
        run: |
          pytest -q --maxfail=1 --disable-warnings \
                 --cov=src --cov-report=xml:coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ðŸš¦ Quality Gate (opcional)
        uses: SonarSource/sonarcloud-quality-gate-action@master
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
S
