name: CI - Tests, Coverage & SonarCloud

on:
  push:
    branches: [ "main", "developer", "certification" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-analyze:
    runs-on: ubuntu-latest

    steps:
      # Checkout del c贸digo
      - name: Checkout del c贸digo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Configurar Python
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Instalar dependencias y fijar versiones
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov flake8 bandit
          pip freeze  #  Esto mostrar谩 las versiones reales instaladas

      # Verificar formato del c贸digo (Linting)
      - name: Linting con Flake8
        run: |
          flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 src --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics

      # Escaneo de seguridad con Bandit
      - name: Escaneo de seguridad con Bandit
        run: |
          bandit -r src -q || true

      # Ejecutar pruebas unitarias con cobertura
      - name: Ejecutar pruebas con cobertura
        run: |
          export PYTHONPATH=$(pwd)
          pytest -q --maxfail=1 --disable-warnings \
                 --cov=src --cov-report=xml:coverage.xml

      # An谩lisis de calidad con SonarCloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Verificaci贸n de Quality Gate (opcional)
      - name:  Quality Gate (opcional)
        uses: SonarSource/sonarcloud-quality-gate-action@v1
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


